# Generated by Django 3.1.7 on 2021-07-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Visitor',
        ),
    ]
