# Generated by Django 3.1.7 on 2021-07-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0002_auto_20210703_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelurusan', models.FloatField()),
                ('elevasi', models.FloatField()),
                ('geologi', models.FloatField()),
                ('jalan', models.FloatField()),
                ('kel', models.FloatField()),
                ('lahan', models.FloatField()),
                ('sungai', models.FloatField()),
                ('tanah', models.FloatField()),
                ('hujan', models.FloatField()),
                ('aspek', models.FloatField()),
            ],
        ),
    ]
