# Generated by Django 3.1.7 on 2021-07-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='kota',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
